### ISSUE TITLE
Add annotation to force running nightly CI on a particular PR

### ISSUE THREAD

**Issue by randombit** [randombit/botan#4414]
In #4413 I modified the nightly.yml file to force it to run the MSVC/GCC sanitizer builds.

It would be nice if the nightly would run either on the schedule *or* if a commit within the PR contains eg "[run nightly]" in the summary line. (I'm not sure if this is possible in GH Actions)

**Comment by reneme** [comment]
The manual trigger for the nightly doesn't cut it?

<img width="665" alt="image" src="https://github.com/user-attachments/assets/af4dd24f-a605-45e5-b03e-5ba000125eac">


... that said, the annotation would be super convenient for sure.

**Comment by randombit** [comment]
TIL yeah that probably is sufficient.

**Comment by reneme** [comment]
There doesn't seem to be a dedicated feature to launch an action on a commit annotation. It would be possible to create a new "trigger" workflow, that runs on push. This could then contain a job that runs only when the head commit contains a pre-defined annotation. In the job we could use the `gh` CLI tool to launch the nightly build.

Untested, but roughly like this:

```yaml
name: triggers

permissions:
  contents: read

on:
  push

jobs:
  carpe_noctem:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[run nightly]')
    steps:
      - name: Run the nightly
        run: gh workflow run "nightly" --ref "${{ github.ref }}"
```

Alternatively, there are also triggers for adding a label to pull requests. I.e.

```yaml
on:
  pull_request:
    types: [labeled]
    labels: [nightly]
```

... frankly, I think running the workflow manually from the GUI is just fine and less maintenance. 😏
